20200224_modulos_company_invoice
trazzos/cd_vue pull request #11
Opened 2020-02-25 00:50 UTC by loranca

modulo de company (actualizado)
modulo de invoice (actualizado)

2020-02-25 22:20 UTC, mwleinad requested changes

2020-02-25 22:20 UTC, mwleinad commented on Modules/Company/Http/Controllers/CompanyDeleteController.php
> +        $request->validated();
No necesitas el request->validated si de todas maneras estas usando $request->get("id") adelante
$request->validated(); retorna un arreglo de las propiedades validadas del request

2020-02-25 22:20 UTC, mwleinad commented on Modules/Company/Http/Controllers/CompanyDeleteController.php
> +    private $companyDeleteService;
falta phpdoc

2020-02-25 22:20 UTC, mwleinad commented on Modules/Company/Http/Controllers/CompanyGetController.php
> +        $id = $request->get('id');
Le comente a Nestor que la parte de filtros/paginacion me la aviento el fin, para que de ahi se guien, por lo pronto este lo dejemos asi que regrese la lista de todo.

2020-02-25 22:20 UTC, mwleinad commented on Modules/Company/Http/Controllers/CompanyPatchController.php
> +    private $companyPatchService;
phpdoc

2020-02-25 22:20 UTC, mwleinad commented on Modules/Company/Http/Requests/CompanyDeleteValidationRequest.php
> +        return true;
igual el fin trabajare la parte de roles (sencillos, pero para que veamos algo de los policies de laravel.

2020-02-25 22:20 UTC, mwleinad commented on Modules/Company/Http/Requests/CompanyPostValidationRequest.php
> +            'ftr' => 'string|required|min:12|max:13|unique:company',
porque le cambiaron a ftr? o que es ftr?

2020-02-25 22:20 UTC, mwleinad commented on Modules/Company/Http/Requests/CompanyPatchValidationRequest.php
> +            'municipio_id' => 'integer|required',
No necesitas tantos id's solo necesitas el ultimo quizas municipio_id? que seria en verdad city_id
con las relaciones de laravel puedes obtener el pais
$company->city->state->country
porque un city BelongsTo state
a su vez state BelongsTo country

2020-02-25 22:20 UTC, mwleinad commented on Modules/Company/Http/Requests/CompanyPostValidationRequest.php
> +            'municipio_id' => 'integer|required',
city_id y no necesitarias state_id

2020-02-25 22:20 UTC, mwleinad commented on Modules/Company/Models/Company.php
> +    /* protected $hidden = ['id']; */
borrar linea

2020-02-25 22:20 UTC, mwleinad commented on Modules/Company/Services/CompanyDeleteService.php
> +        return $this->companyRepo->deleteWhere("id","=",$id);
$this->companyRepo->delete($id)

2020-02-25 22:20 UTC, mwleinad commented on Modules/Company/Services/CompanyPatchService.php
> +        $company = $this->companyRepo->update($data,$id,"id");
por default ya jala el id
tpms quedaria asi
$this->companyRepo->update($data,$id);

2020-02-25 22:20 UTC, mwleinad commented on Modules/Company/Services/CompanyPatchService.php
> +        if(!$company) {
no necesitas este, -> update regresa un boolean, verdadero si hizo el update y falso si no.
creo que la que quieres usar es 
->updateAndReturn para que te regrese el modelo ya actualizado

2020-02-25 22:20 UTC, mwleinad commented on Modules/Invoice/Database/Seeders/InvoiceDatabaseSeeder.php
> +namespace Modules\Invoice\Database\Seeders;
borrar archivo

2020-02-25 22:20 UTC, mwleinad commented on Modules/Invoice/Http/Controllers/InvoiceDeleteController.php
> +    private $invoiceDeleteService;
phpdoc

2020-02-25 22:20 UTC, mwleinad commented on Modules/Invoice/Http/Controllers/InvoiceDeleteController.php
> +        $request->validated();
mismo caso, no necesitas esta linea

2020-02-25 22:20 UTC, mwleinad commented on Modules/Invoice/Http/Controllers/InvoiceGetController.php
> +    private $invoiceGetService;
phpdoc

2020-02-25 22:20 UTC, mwleinad commented on Modules/Invoice/Http/Controllers/InvoicePatchController.php
> +    private $invoicePatchService;
phpdoc

2020-02-25 22:20 UTC, mwleinad commented on Modules/Invoice/Http/Controllers/InvoicePostController.php
> +    private $invoiceCreateService;
phpdoc

2020-02-25 22:20 UTC, mwleinad commented on Modules/Invoice/Models/Invoice.php
> +    /* protected $hidden = ['id']; */
borrar linea

2020-02-25 22:20 UTC, mwleinad commented on Modules/Invoice/Resources/views/index.blade.php
> +@section('content')
borrar archivo

2020-02-25 22:20 UTC, mwleinad commented on Modules/Invoice/Resources/views/layouts/master.blade.php
> +<!DOCTYPE html>
borrar archivo

2020-02-25 22:20 UTC, mwleinad commented on Modules/Invoice/Services/InvoiceDeleteService.php
> +        return $this->invoiceRepo->deleteWhere("id","=",$id);
mismo caso con company

2020-02-25 22:20 UTC, mwleinad commented on Modules/Invoice/Services/InvoicePatchService.php
> +        $invoice = $this->invoiceRepo->update($data,$id,"id");
mismo caso con company

2020-02-25 22:20 UTC, mwleinad commented on database/migrations/2020_02_24_230838_create_company_table.php
> +            $table->integer('location_id');
aqui como te comente solo es necesario tener el ultimo nivel y siempre y cuando tengas bien tus relaciones en los modelos laravel debe de resolver lo demas

2020-02-25 22:20 UTC, mwleinad commented on database/migrations/2020_02_24_230838_create_company_table.php
> +            $table->string('adress')->nullable();
address

2020-03-03 20:31 UTC, mwleinad requested changes

2020-03-03 20:31 UTC, mwleinad commented on Modules/Company/Services/CompanyPatchService.php
> +        $company = $this->companyRepo->update($data,$id);
updateAndReturn, de lo contrario $company sera falso/verdadero y quieres regresar todo el modelo no?

2020-03-03 20:31 UTC, mwleinad commented on Modules/Invoice/Services/InvoicePatchService.php
> +        $invoice = $this->invoiceRepo->update($data,$id);
igual aqi

2020-03-05 17:50 UTC, mwleinad requested changes

2020-03-05 17:50 UTC, mwleinad commented on Modules/Company/Http/Requests/CompanyPatchValidationRequest.php
> +            'email' => 'string|required',
email|required
https://laravel.com/docs/5.8/validation#available-validation-rules
hay que ver que otras se pueden aplicar

2020-03-05 17:50 UTC, mwleinad commented on Modules/Company/Http/Requests/CompanyPatchValidationRequest.php
> +            'municipio_id' => 'string|required',
int|required para los ids no?

2020-03-05 17:50 UTC, mwleinad commented on Modules/Company/Http/Requests/CompanyPostValidationRequest.php
> +            'email' => 'string|required',
mismo caso

2020-03-07 23:22 UTC, mwleinad requested changes

2020-03-07 23:22 UTC, mwleinad commented on database/migrations/2020_02_24_230838_create_company_table.php
> +            $table->string('location_id');
porque le cambiaste a string?

2020-03-09 18:15 UTC, loranca commented on Modules/Company/Http/Requests/CompanyPostValidationRequest.php
> +            'ftr' => 'string|required|min:12|max:13|unique:company',
ftr es el rfc, asi le puso nestor.

2020-03-09 18:16 UTC, loranca commented on Modules/Company/Http/Requests/CompanyPatchValidationRequest.php
> +            'municipio_id' => 'integer|required',
no se tienen tablas en la bd, se estan consultando desde api del inegi.

2020-03-09 18:17 UTC, loranca commented on Modules/Invoice/Http/Controllers/InvoiceDeleteController.php
> +    private $invoiceDeleteService;
hecho

2020-03-09 18:17 UTC, loranca commented on Modules/Invoice/Http/Controllers/InvoiceGetController.php
> +    private $invoiceGetService;
hecho

2020-03-09 18:17 UTC, loranca commented on Modules/Invoice/Http/Controllers/InvoicePatchController.php
> +    private $invoicePatchService;
hecho

2020-03-09 18:17 UTC, loranca commented on Modules/Invoice/Http/Controllers/InvoicePostController.php
> +    private $invoiceCreateService;
hecho

2020-03-09 18:18 UTC, loranca commented on Modules/Invoice/Resources/views/index.blade.php
> +@section('content')
hecho

2020-03-09 18:18 UTC, loranca commented on Modules/Invoice/Resources/views/layouts/master.blade.php
> +<!DOCTYPE html>
hecho

2020-03-09 18:19 UTC, loranca commented on database/migrations/2020_02_24_230838_create_company_table.php
> +            $table->integer('location_id');
se traen desde las api's del inegi.

2020-03-09 18:19 UTC, loranca commented on Modules/Company/Services/CompanyPatchService.php
> +        $company = $this->companyRepo->update($data,$id);
hecho

2020-03-09 18:20 UTC, loranca commented on Modules/Invoice/Services/InvoicePatchService.php
> +        $invoice = $this->invoiceRepo->update($data,$id);
hecho

2020-03-09 18:22 UTC, loranca commented on Modules/Company/Http/Requests/CompanyPatchValidationRequest.php
> +            'municipio_id' => 'string|required',
el inegi los maneja a 3 para municipios(101) y 4 dígitos para localidades (0001)

2020-03-09 18:22 UTC, loranca commented on database/migrations/2020_02_24_230838_create_company_table.php
> +            $table->string('location_id');
uso de api's inegi.

2020-03-10 20:10 UTC, mwleinad approved these changes

2020-03-10 20:10 UTC, mwleinad commented on Modules/Company/Services/CompanyGetService.php
> +        //Para aplicar filtros, hay que llamar a esta funcion, por ejemplo para company seria $this->companyRepo
ya no son necesarios los comentarios

2020-03-10 20:10 UTC, mwleinad commented on Modules/Invoice/Services/InvoicePatchService.php
> +        $invoice = $this->invoiceRepo->updateAndReturn($data,$id);
aqui puedes hacer return sin necesidad de asignar el valor

2020-03-10 20:12 UTC, merged

2020-03-10 20:13 UTC, loranca commented on Modules/Company/Services/CompanyGetService.php
> +        //Para aplicar filtros, hay que llamar a esta funcion, por ejemplo para company seria $this->companyRepo
ok