20200310_modulo_proyectos
trazzos/cd_vue pull request #17
Opened 2020-03-10 21:50 UTC by evolycorp

2020-03-12 22:43 UTC, mwleinad requested changes

2020-03-12 22:43 UTC, mwleinad commented on Modules/Project/Database/Seeders/ProjectDatabaseSeeder.php
> +     * Run the database seeds.
borrar

2020-03-12 22:43 UTC, mwleinad commented on Modules/Project/Http/Requests/ProjectDeleteValidationRequest.php
> +    /*public function messages(){
borrar

2020-03-12 22:43 UTC, mwleinad commented on Modules/Project/Models/Project.php
> +    protected $fillable = [
en vez de usar el fillable y poner todos
puedes usar
protected $guarded = []; 
para los que NO quieras que se pueda hacer update

2020-03-12 22:43 UTC, mwleinad commented on Modules/Project/Models/Project.php
> +    public function getJWTIdentifier() {
estos no los lleva, y la siguiente, solo es para la de user

2020-03-12 22:43 UTC, mwleinad commented on Modules/Project/Models/Project.php
> +class Project extends Authenticatable implements JWTSubject
no extiende autenticable ni implementa jwtsubject

2020-03-12 22:43 UTC, mwleinad commented on Modules/Project/Resources/views/layouts/master.blade.php
> +        <meta name="viewport" content="width=device-width, initial-scale=1">
borrar

2020-03-12 22:43 UTC, mwleinad commented on Modules/Project/Services/Filters/ProjectCompany_Id.php
> +class ProjectCompany_Id extends FilterAbstract implements CriteriaInterface {
el nombre del archivo no debe de llevar guion bajo es
ProjectCompanyId

2020-03-12 23:16 UTC, evolycorp commented on Modules/Project/Models/Project.php
> +    protected $fillable = [
De acuerdo

2020-03-12 23:18 UTC, evolycorp commented on Modules/Project/Models/Project.php
> +    public function getJWTIdentifier() {
Vale

2020-03-12 23:23 UTC, evolycorp commented on Modules/Project/Services/Filters/ProjectCompany_Id.php
> +class ProjectCompany_Id extends FilterAbstract implements CriteriaInterface {
Solo el nombre del archivo? La clase si lleva?

2020-03-12 23:28 UTC, evolycorp commented on Modules/Project/Services/Filters/ProjectCompany_Id.php
> +class ProjectCompany_Id extends FilterAbstract implements CriteriaInterface {
Listo

2020-03-13 18:58 UTC, mwleinad approved these changes

2020-03-13 18:58 UTC, merged