20200310_announcement
trazzos/cd_vue pull request #18
Opened 2020-03-11 05:42 UTC by loranca

modulo de convocatorias, 
modulo de convocatorias_tipo (solo hice la parte del GET ya que se usa en el formulario de alta de convocatoria)

2020-03-12 22:18 UTC, mwleinad requested changes

2020-03-12 22:18 UTC, mwleinad commented on Modules/Announcement/Http/Requests/AnnouncementPostValidationRequest.php
> +            'fecha' =>'required',
fecha?

2020-03-12 22:18 UTC, mwleinad commented on Modules/Announcement/Models/Announcement.php
> +        return $this->hasMany(AnnouncementType::class);
borrar

2020-03-12 22:18 UTC, mwleinad commented on Modules/Announcement/Services/AnnouncementGetService.php
> +        //$announcement->load('announcement_type');
borrar

2020-03-12 22:18 UTC, mwleinad commented on Modules/AnnouncementType/Services/AnnouncementTypeGetService.php
> +     * At this point everything is validated, we shouldn't check anything else
hay que borrar mis comentarios de ejemplo

2020-03-12 22:18 UTC, mwleinad commented on database/migrations/2020_03_10_170058_create_announcement_table.php
> +            $table->string('announcement_type_id');
no es necesario ambas

2020-03-12 22:18 UTC, mwleinad commented on database/migrations/2020_03_10_170058_create_announcement_table.php
> +            $table->string('fecha');
date

2020-03-12 22:18 UTC, mwleinad commented on database/seeds/announcement_typeTableSeeder.php
> +            ['name' => 'ESTATAL'],
siendo asi siento que un config es mejor simplemente guarda tal cual en la base
ESTATAL, FEDERAL etc

2020-03-24 00:23 UTC, loranca commented on database/migrations/2020_03_10_170058_create_announcement_table.php
> +            $table->string('fecha');
ok

2020-03-24 00:25 UTC, loranca commented on database/seeds/announcement_typeTableSeeder.php
> +            ['name' => 'ESTATAL'],
acordamos en tener las tablas aunque sea para consulta.

2020-03-24 14:36 UTC, mwleinad approved these changes

2020-03-24 14:37 UTC, merged