20200226_module_stage_task
trazzos/cd_vue pull request #20
Opened 2020-03-14 19:50 UTC by aristasoluciones

se agrega paginacion en modulo stage

2020-03-16 14:21 UTC, mwleinad requested changes

2020-03-16 14:21 UTC, mwleinad commented on Modules/Stage/Models/Stage.php
> +use \Askedio\SoftCascade\Traits\SoftCascadeTrait;
se te paso el \ al principio

2020-03-16 14:21 UTC, mwleinad commented on Modules/Stage/Services/StagePatchService.php
> +    private function normalizeData(User $user, array $data) {
digo, en teoria esto no seria necesario no? 
mi recomendacion es solo poner esta funcion si se requiere hacer algun tipo de normalizacion ya que ahorita solo estas regresando lo mismo

2020-03-16 14:21 UTC, mwleinad commented on Modules/Task/Http/Requests/TaskGetValidationRequest.php
> +            'predicates' => 'array|nullable',
Esto no es necesario hacerlo pero si nos fijamos este codigo esta repetido varias veces, se puede hacer 2 cosas
un validador customizado para poner algo como 
'predicates => 'array|nullable|predicates' (esto manda a llamar a una funcion personalizada)
o
en el config de validacion agregas todo este arreglo desde predicates hasta per_page y haces algo como
return config('validation.predicates')

2020-03-16 14:21 UTC, mwleinad commented on composer.json
> +        "tymon/jwt-auth": "1.0.0-rc.5.1"
porque le quitaste la de ext-json?

2020-03-17 19:24 UTC, aristasoluciones reviewed
Me lo revisas

2020-03-17 19:24 UTC, aristasoluciones commented on composer.json
> +        "tymon/jwt-auth": "1.0.0-rc.5.1"
No la quite, se acomodo mas arriba, saber que hizo composer

2020-03-18 15:58 UTC, mwleinad approved these changes

2020-03-18 15:58 UTC, mwleinad commented on config/validation.php
> +    'default' => [
yo lo llamaria default_http_get 
para que sea mas "verboso"

2020-03-19 16:44 UTC, merged