20200220_modulo_usuarios
trazzos/cd_vue pull request #7
Opened 2020-02-21 02:29 UTC by evolycorp

2020-02-21 20:12 UTC, mwleinad requested changes
Varios detallitos

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Database/Seeders/UserDatabaseSeeder.php
> +namespace Modules\User\Database\Seeders;
borrar archivo

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Http/Controllers/UserDeleteController.php
> +     * UserGetController constructor.
nombre mal

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Http/Controllers/UserDeleteController.php
> + * Class UserPostController
nombre mal

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Http/Controllers/UserDeleteController.php
> +    private $userDeleteService;
falta phpdoc

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Http/Controllers/UserGetController.php
> +    private $userGetService;
falta phpdoc

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Http/Controllers/UserGetController.php
> +        if(!$id)
Varias cositas
de entrada los if siempre con llaves

if(!$id) {
            $response = $this->userGetService->list(); //TODO temporary
} else {
            $response = $this->userGetService->info($id); //TODO pass real id
}

pero seria mejor usar un ternario
$response = isset($id) 
    ? $this->userGetService->list(); //TODO temporary
    : $this->userGetService->info($id); //TODO pass real id

Peeeeeeero, ahora si vamos a empezar a hacer bien el GET
Ya revise y de input puedes recibir ya sea un id o un array de ids (o filtros en un futuro)
pero de output siempre seria una colleccion de usuarios (aunque sea 1)

Para el input cuando llegue al servicio ya seria un array de ids. Lo que significa que en tu ValidationRequest debes de transformar ese $id en un arreglo (si no le hayas dime y yo lo hago maniana igual)

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Http/Controllers/UserPatchController.php
> +     * UserGetController constructor.
nombre mal

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Http/Controllers/UserPatchController.php
> +    private $userPatchController;
falta phpdoc

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Http/Controllers/UserPostController.php
> +     * UserGetController constructor.
nombre mal

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Http/Controllers/UserPostController.php
> +    private $userCreateService;
falta phpdoc

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Http/Requests/UserDeleteValidationRequest.php
> +            'id' => 'integer|required'
este debe de ser un uuid no?

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Http/Requests/UserDeleteValidationRequest.php
> + * Class UserPostValidationRequest
nombre mal

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Http/Requests/UserGetValidationRequest.php
> +            //'id' => 'integer|required'
hay una funcion para sobreescribir la validacion y que puedas hacer lo que te dije de cambiar por un arreglo
se ve mas o menos asi
    /**
     * @param Factory $factory
     * @return \Illuminate\Validation\Validator
     * By overriding the validator method on the factory you can add custom rules per each type of resource/api call
     */
    public function validator(Factory $factory) : Validator {
        $validator = $factory->make($this->getParamsForValidation(), $this->rules(), $this->messages(), $this->attributes());

        $apiObject = $this->apiFlatGetFactory->create($this->resource);
        $validator = $apiObject->validator($validator, $this->request);

        if(!$validator->fails()) {
            $this->addParametersToRequest($apiObject);
        }

        return $validator;
    }

    /**
     * Builds the array of data we need to validate and appends identifier from the url when needed.
     * We only ever want to have one identifier/identifiers property included for validation. Never both.
     * Priority order: identifiers from the body, identifier from body, identifier from url
     *
     * @return array
     */
    private function getParamsForValidation() : array {
        $allParams = $this->input();

        if(array_key_exists('identifiers', $allParams)) 
        {
            unset($allParams['identifier']);
        }
        else if(!array_key_exists('identifier', $allParams) && $this->route()->identifier) 
        {
            $allParams['identifier'] = $this->route()->identifier;
        }

        return $allParams;
    }

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Http/Requests/UserPatchValidationRequest.php
> + * Class UserPostValidationRequest
nombre mal

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Http/Requests/UserPatchValidationRequest.php
> +            'id' => 'integer|required',
este es uuid no?

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Http/Requests/UserPostValidationRequest.php
> +    /*public function messages(){
borrar

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Models/User.php
> +    use SoftDeletes;
Viendo, no recuerdo si quedamos que user seria uuid o solo integer.
Si es uuid necesitas hacer una migracion para cambiar el tipo de dato. y usar el trait de uuid (como company)

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Resources/views/index.blade.php
> +    <h1>Hello World</h1>
borrar
tambien borra
app.scss
y app.js

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Resources/views/layouts/master.blade.php
> +    <head>
borrar

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Routes/api.php
> +//TODO we are not using any authentication yet.
borrar, yo trabajare en esto maniana

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Http/Controllers/UserDeleteController.php
> +        return $this->handleAjaxJsonResponse($response);
este deberia de regresar un estatus 204. Voy a ver si la function handleAjaxJsonResponse soporta regresar status sino pues yo lo agrego

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Services/UserDeleteService.php
> +        return $user;
no regresariamos nada

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Services/UserDeleteService.php
> +        $user = $this->userRepo->findBy('id', $id);
cuando se borra algo por convenio no se devuelve nada ...
en el HTTP se devuelve un estatus 204 (No Content)

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Services/UserDeleteService.php
> +        $user = $this->userRepo->findBy('id', $id);
no creo que sea necesario

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Services/UserGetService.php
> +    public function info($id) : ?User {
como el punto es siempre pasar un arreglo de 0, 1 o mas ids, pues ya no necesitas 2 funciones, sino ya la de list puede ser para ambas

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Services/UserGetService.php
> +        /*if(!$user) {
hay que tirar la exception si la colleccion es vacia

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Services/UserGetService.php
> +        $companies= $this->userRepo->all();
$users

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Services/UserGetService.php
> +        return $companies;
return $users

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Services/UserUpdateService.php
> +     * UserGetService constructor.
nombre mal

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Services/UserUpdateService.php
> +        $this->userRepo->update($data, $data["id"]);
revisa que id este en el arreglo de $guarded del modelo de user para que no puedan actualizar el id

2020-02-21 20:12 UTC, mwleinad commented on Modules/User/Services/UserUpdateService.php
> +        $user = $this->userRepo->findBy('id', $data["id"]);
checate si tenemos la funcion updateAndReturn, que hace esto justamente.

2020-02-21 20:12 UTC, mwleinad commented on database/migrations/2020_02_19_011107_create_user_table.php
> +            $table->bigIncrements('id');
hay que ver si este seria uuid o int

2020-02-22 19:13 UTC, evolycorp commented on Modules/User/Http/Controllers/UserGetController.php
> +        if(!$id)
Lo intenté pero no pude :(

2020-02-22 19:28 UTC, evolycorp commented on Modules/User/Http/Requests/UserDeleteValidationRequest.php
> +            'id' => 'integer|required'
tengo entendido que no porque no van a crear usuarios desde la aplicacion movil

2020-02-22 19:30 UTC, evolycorp commented on Modules/User/Http/Requests/UserPatchValidationRequest.php
> +            'id' => 'integer|required',
Tampoco

2020-02-22 19:51 UTC, evolycorp commented on Modules/User/Services/UserUpdateService.php
> +        $this->userRepo->update($data, $data["id"]);
Si está

2020-02-23 00:52 UTC, mwleinad requested changes

2020-02-23 00:52 UTC, mwleinad commented on Modules/User/Http/Controllers/UserGetController.php
> +        var_dump($data);exit;
quitar

2020-02-23 00:52 UTC, mwleinad commented on Modules/User/Services/UserGetService.php
> +        foreach($data AS $clave=>$value){
mmm para que hiciste esto aqui?
creo no necesitas el foreach
puedes hacer
$this->userRepo->whereIn($ids); //$ids es un arreglo de ids $ids = [1, 2, 3, 4]

2020-02-23 00:52 UTC, mwleinad commented on Modules/User/Services/UserGetService.php
> +        $collection = Collection::make($users);
es mas facil usar el helper de laravel 
$collection = collect($users);
pero no lo necesitarias de todas maneras si usas el whereIn

2020-02-23 00:52 UTC, mwleinad commented on Modules/User/Services/UserUpdateService.php
> +        $user = $this->userRepo->updateAndReturn($data, $data["id"]);
puedes hacer directo 
`return $this->userRepo->updateAndReturn($data, $data["id"]);`

2020-02-25 00:33 UTC, evolycorp commented on Modules/User/Http/Requests/UserGetValidationRequest.php
> +            //'id' => 'integer|required'
Esta parte no entendí que onda

2020-02-25 21:47 UTC, mwleinad requested changes

2020-02-25 21:47 UTC, mwleinad commented on Modules/User/Services/UserGetService.php
> +        if(!$user) {
$user no esta declarado

2020-02-25 22:26 UTC, mwleinad requested changes

2020-02-25 22:26 UTC, mwleinad commented on Modules/User/Routes/api.php
> +    Route::get('', 'UserGetController')->name('userGet');
Hay que meter las rutas que requieran "login" dentro del middleware de jwt.auth

2020-02-26 21:39 UTC, merged